version: '3.3'

services:
  db:
    image: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - network-teste 

  web:
    build: .
    hostname: web
    env_file:
    - .env
    volumes:
      - .:/webapps
    ports:
      - "8001:8001"
    links:
      - db
    depends_on:
      - db
    networks:
      - network-teste 
      
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf .
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - network-teste 

networks:
    network-teste: